@echo off
mkdir "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Roman Set\P1010037.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\roman-1.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Roman Set\P1010033.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\roman-2.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Roman Set\P1010049.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\roman-3.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Roman Set\P1010094.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\roman-4.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Roman Set\P1010101.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\roman-5.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Egyptian Sets\DSCN5380.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\egyptian-1.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Egyptian Sets\DSCN5564.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\egyptian-2.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Atlas Studios\IMG_6696.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\atlas-1.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Atlas Studios\IMG_6709.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\atlas-2.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Atlas Studios\IMG_9270.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\atlas-3.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Artisanat Studio\DSCN5402.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\artisanat-1.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Artisanat Studio\DSCN5409.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\artisanat-2.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Artisanat Studio\IMG_0486.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\artisanat-3.jpg"
copy "c:\Users\Younes\Desktop\dramaker prodactions\public\all pic\Artisanat Studio\IMG_0514.JPG" "c:\Users\Younes\Desktop\dramaker prodactions\public\studios\moodboard\artisanat-4.jpg"
echo "Copies complete"
